[workspace]
members = ["src/did", "src/dip721", "src/sell_contract"]
resolver = "2"

[workspace.package]
authors = ["Christian Visintin <christian.visintin@veeso.dev>"]
edition = "2021"
license = "SEE LICENSE IN LICENSE"
readme = "README.md"
repository = "https://github.com/veeso-dev/dilazionato"
version = "0.1.0"

[workspace.dependencies]
async-trait = "0.1"
candid = "0.9"
chrono = "0.4"
ic-cdk = "0.11"
ic-cdk-macros = "0.8"
ic-stable-structures = "0.6"
itertools = "0.11"
log = "0.4"
num-bigint = "0.4"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"

[profile.dev]
debug = false

[profile.dev.package."*"]
opt-level = 2

[profile.dev.build-override]
opt-level = 2

[profile.release]
lto = true
opt-level = 'z'
