[workspace]
members = ["src/did", "src/dip721", "src/deferred", "src/fly", "src/icrc"]
resolver = "2"

[workspace.package]
authors = ["Christian Visintin <christian.visintin@veeso.dev>"]
edition = "2021"
license = "SEE LICENSE IN LICENSE"
readme = "README.md"
repository = "https://github.com/veeso-dev/deferred"
version = "0.1.0"

[workspace.dependencies]
async-trait = "0.1"
bytes = "1.5"
candid = "0.9"
chrono = "0.4"
getrandom = { version = "0.2", features = ["js"] }
ic-cdk = "0.11"
ic-cdk-macros = "0.8"
ic-cdk-timers = "0.5"
ic-stable-structures = "0.6"
icrc-ledger-types = "0.1"
itertools = "0.12"
num-bigint = "0.4"
num-traits = "0.2"
rand = { version = "0.8", features = ["std_rng", "small_rng"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"
time = "0.1"

[profile.dev]
debug = false

[profile.dev.package."*"]
opt-level = 2

[profile.dev.build-override]
opt-level = 2

[profile.release]
lto = true
opt-level = 'z'
