[workspace]
members = ["src/did", "src/dip721", "src/dilazionato", "src/fly", "src/icrc"]
resolver = "2"

[workspace.package]
authors = ["Christian Visintin <christian.visintin@veeso.dev>"]
edition = "2021"
license = "SEE LICENSE IN LICENSE"
readme = "README.md"
repository = "https://github.com/veeso-dev/dilazionato"
version = "0.1.0"

[workspace.dependencies]
async-trait = "0.1"
candid = "0.9"
ic-cdk = "0.11"
ic-cdk-macros = "0.8"
ic-stable-structures = "0.6"
icrc-ledger-types = "0.1"
itertools = "0.11"
num-bigint = "0.4"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0"
time = "0.1"

[profile.dev]
debug = false

[profile.dev.package."*"]
opt-level = 2

[profile.dev.build-override]
opt-level = 2

[profile.release]
lto = true
opt-level = 'z'
