[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.dfx-build]
description = "Build canisters"
dependencies = []
script = "./scripts/dfx-build.sh"
workspace = false

[tasks.run]
description = "Run app"
dependencies = []
command = "cargo"
args = ["run"]
workspace = false

[tasks.test]
description = "Run unit tests"
command = "cargo"
args = ["test", "--lib"]
dependencies = ["did"]
workspace = false

[tasks.integration-tests]
description = "Run integration tests"
script = "./scripts/integration-tests.sh"
dependencies = ["did", "dfx-build"]
workspace = false

[tasks.deploy-local]
description = "Deploy testnet with dfx"
script = "./scripts/deploy_local.sh"
dependencies = ["dfx-setup", "dfx-build", "did"]
workspace = false

[tasks.lint]
description = "Run lint"
command = "cargo"
args = ["clippy", "--", "-Dwarnings"]
workspace = false

[tasks.format]
description = "Run the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--all"]

[tasks.check-format]
description = "Run the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.did]
description = "Generate did files"
dependencies = [
  "dfx-pull",
  "deferred_data_did",
  "deferred_minter_did",
  "dfx-generate",
]
workspace = false

[tasks.dfx-pull]
description = "Pull dfx"
script = "dfx deps pull"
workspace = false

[tasks.deferred_data_did]
description = "Generate did files for deferred"
script = "cargo run --bin deferred_data_did  --features did > ic/deferred_data/deferred_data.did"
workspace = false

[tasks.deferred_minter_did]
description = "Generate did files for deferred"
script = "cargo run --bin deferred_minter_did  --features did > ic/deferred_minter/deferred_minter.did"
workspace = false

[tasks.dfx-generate]
description = "Generate dfx did"
command = "dfx"
args = ["generate"]
workspace = false

[tasks.dfx-setup]
description = "setup dfx"
script = "./scripts/dfx-setup.sh"
workspace = false
