[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build]
description = "Build canisters"
dependencies = []
script = "./scripts/dfx-build.sh"
workspace = false

[tasks.run]
description = "Run app"
dependencies = []
command = "cargo"
args = ["run"]
workspace = false

[tasks.test]
description = "Run unit tests"
command = "cargo"
args = ["test", "--lib"]
dependencies = ["did"]
workspace = false

[tasks.integration-tests]
description = "Run integration tests"
script = "./scripts/integration-tests.sh"
dependencies = ["did", "build"]
workspace = false

[tasks.deploy-local]
description = "Deploy testnet with dfx"
script = "./scripts/deploy_local.sh"
dependencies = ["dfx-setup", "build", "did"]
workspace = false

[tasks.lint]
description = "Run lint"
command = "cargo"
args = ["clippy", "--", "-Dwarnings"]
workspace = false

[tasks.format]
description = "Run the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--all"]

[tasks.check-format]
description = "Run the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.did]
description = "Generate did files"
dependencies = [
  "deferred-did",
  "ekoke-erc20-swap-did",
  "ekoke-liquidity-pool-did",
  "ekoke-reward-pool-did",
  "marketplace-did",
  "dfx-generate",
]
workspace = false

[tasks.deferred-did]
description = "Generate did files for deferred"
script = "cargo run --bin deferred-did  --features did > src/deferred/deferred.did"
workspace = false

[tasks.ekoke-erc20-swap-did]
description = "Generate did files for ekoke-erc20-swap"
script = "cargo run --bin ekoke-erc20-swap-did  --features did > src/ekoke_erc20_swap/ekoke-erc20-swap.did"
workspace = false

[tasks.ekoke-liquidity-pool-did]
description = "Generate did files for ekoke-liquidity-pool"
script = "cargo run --bin ekoke-liquidity-pool-did  --features did > src/ekoke_liquidity_pool/ekoke-liquidity-pool.did"
workspace = false

[tasks.ekoke-reward-pool-did]
description = "Generate did files for ekoke-reward-pool"
script = "cargo run --bin ekoke-reward-pool-did  --features did > src/ekoke_reward_pool/ekoke-reward-pool.did"
workspace = false

[tasks.marketplace-did]
description = "Generate did files for marketplace"
script = "cargo run --bin marketplace-did  --features did > src/marketplace/marketplace.did"
workspace = false

[tasks.dfx-generate]
description = "Generate dfx did"
command = "dfx"
args = ["generate"]
workspace = false

[tasks.dfx-setup]
description = "setup dfx"
script = "./scripts/dfx-setup.sh"
workspace = false
