[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.build]
description = "Build canisters"
dependencies = []
command = "dfx"
args = ["build"]
workspace = false

[tasks.run]
description = "Run app"
dependencies = []
command = "cargo"
args = ["run"]
workspace = false

[tasks.test]
description = "Run unit tests"
command = "cargo"
args = ["test", "--lib"]
dependencies = ["did"]
workspace = false

[tasks.integration-tests]
description = "Run integration tests"
command = "cargo"
args = ["test", "--test", "integration_tests"]
dependencies = ["did", "build"]
workspace = false

[tasks.deploy-local]
description = "Deploy testnet with dfx"
script = "./scripts/deploy_local.sh"
dependencies = ["dfx-setup", "build", "did"]
workspace = false

[tasks.lint]
description = "Run lint"
command = "cargo"
args = ["clippy", "--", "-Dwarnings"]
workspace = false

[tasks.format]
description = "Run the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--all"]

[tasks.check-format]
description = "Run the cargo rustfmt plugin."
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.did]
description = "Generate did files"
dependencies = ["deferred-did", "fly-did", "dfx-generate"]
workspace = false

[tasks.deferred-did]
description = "Generate did files for deferred"
script = "cargo run --bin deferred-did  --features did > src/deferred/deferred.did"
workspace = false

[tasks.fly-did]
description = "Generate did files for fly"
script = "cargo run --bin fly-did  --features did > src/fly/fly.did"
workspace = false

[tasks.dfx-generate]
description = "Generate dfx did"
command = "dfx"
args = ["generate"]
workspace = false

[tasks.dfx-setup]
description = "setup dfx"
script = "dfx stop; dfx start --background; dfx canister create deferred; dfx canister create fly"
workspace = false
