name: build-test

on:
  pull_request:
    paths-ignore:
      - "*.md"
  push:
    paths-ignore:
      - "*.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libssl-dev pkg-config jq && cargo install cargo-make
      - name: Install Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dfx
        run: echo y | sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Test
        run: cargo make test
      - name: Integration tests
        run: cargo make deploy-local
      - name: Format
        run: cargo make check-format
      - name: Clippy
        run: cargo make lint
