name: ethereum
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: yarn --ignore-scripts
        shell: bash
        working-directory: ./ethereum
      - name: tests
        run: |
          cp .env.github .env
          yarn compile
          yarn test
        working-directory: ./ethereum
      - name: Create local node and deploy
        run: |
          cp .env.github .env
          yarn compile
          yarn hardhat node &
          sleep 2
          yarn deploy:localhost ekoke
          yarn deploy:localhost deferred
          yarn deploy:localhost --ekoke 0x92fBA9067844A419A1C394197aE406768555F71b ekoke-presale
          yarn deploy:localhost --ekoke 0x92fBA9067844A419A1C394197aE406768555F71b --deferred 0x92fBA9067844A419A1C394197aE406768555F71b reward-pool
          yarn deploy:localhost --ekoke 0x92fBA9067844A419A1C394197aE406768555F71b --deferred 0x92fBA9067844A419A1C394197aE406768555F71b --usderc20 0x92fBA9067844A419A1C394197aE406768555F71b marketplace
        working-directory: ./ethereum
